### ISSUE TITLE
有关论文中色调映射函数的问题

### ISSUE THREAD

**Issue by yehuixie** [ltkong218/SAFNet#8]
作者您好，我想请问一下论文Fig.6和补充材料Fig.4的定性比较中采用的色调映射函数是否为μ-law函数？我采用μ-law函数得到的结果如下：
![003](https://github.com/user-attachments/assets/4103d772-6829-418f-ac7b-f5eb476a9607)
![008_gt](https://github.com/user-attachments/assets/248ac0a8-f660-4088-9f39-65e4174e5ef9)
![012](https://github.com/user-attachments/assets/bd2e6b1c-eb5d-4170-914f-446097330a64)

这与论文论文Fig.6和补充材料Fig.4的图片有所不同，因此想问下论文中定性比较采用的是哪种色调映射函数？

**Comment by ltkong218** [comment]
I use the [Photomatix](https://www.hdrsoft.com/) software for tone mapping of the proposed Challenge123 dataset.
The tone mapping approaches for each of the 27 HDR images in Challenge123 test set are as follows:
001_Realistic, 002_Photographic, 003_Realistic, 004_Realistic, 005_Photographic, 006_Realistic, 007_Realistic, 008_Balanced, 009_Balanced, 010_Balanced, 011_Balanced, 012_Balanced, 013_Balanced, 014_Photographic, 015_Photographic, 016_Balanced, 017_Realistic, 018_Realistic, 019_Balanced, 020_Balanced, 021_Photographic, 022_Realistic, 023_Realistic, 024_Photographic, 025_Realistic, 026_Realistic, 027_Balanced.

Thanks.

**Comment by yehuixie** [comment]
谢谢！
